image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      nvm use 14
      nvm alias default 14
      yarn
      yarn build
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==
