image: gitpod/workspace-mongodb
tasks:
  - init: |
      nvm install 14
      nvm use 14
      yarn
      yarn build
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==